on: [push, pull_request]

name: Build from SVN

concurrency:
  group: ${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    timeout-minutes: 120
    env:
      R_CRAN_WEB: "https://cran.rstudio.com"
      CRAN_RSYNC: 'mirrors.nic.cz::CRAN'
    steps:

    - name: Prepare git
      run: git config --global core.autocrlf false

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        install: git make perl
        update: true

    - name: "Setup rtools43 toolchain"
      shell: bash
      run: |
        url="https://github.com/r-windows/files/releases/download/5493/rtools43-toolchain-libs-base-5493.tar.zst"
        curl -sSL $url | tar x --zstd -C /c/ || true
        echo "c:/x86_64-w64-mingw32.static.posix/bin" >> $GITHUB_PATH

    - name: System dependencies
      shell: powershell
      run: |
        Import-Module .\.github\workflows\scripts.ps1
        SetTimezone
        InstallRtoolsExe
        InstallMiktex -ErrorAction SilentlyContinue;

    - name: "Fix rsync-recommended"
      shell: bash
      run: sed -i.bak 's/rsync -rc/rsync -r/' tools/rsync-recommended

    - name: Build and Check
      run: ./.github/workflows/rtools40-build.sh

    - name: Print failed tests
      if: failure()
      shell: bash
      run: tail -n100 tests/*.fail
